/******************************************************************************
* File Name: network_credentials.h
*
* Description: This file is the public interface for Ethernet credentials and
* TLS credentials.
*
* Related Document: See README.md
*
*******************************************************************************
* Copyright 2022-2024, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef NETWORK_CREDENTIALS_H_
#define NETWORK_CREDENTIALS_H_

/*******************************************************************************
* Macros
********************************************************************************/

/* TCP client certificate. Copy from the TCP client certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keyCLIENT_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIICAzCCAakCFD3ZEPLPA3JQLvR7Yvx/KGXlYleHMAoGCCqGSM49BAMCMIGBMQsw\n"\
"CQYDVQQGEwJJTjEMMAoGA1UECAwDXEtBMREwDwYDVQQHDAhCYW5nbG9yZTERMA8G\n"\
"A1UECgwISW5maW5lb24xCzAJBgNVBAsMAkNZMQ0wCwYDVQQDDARteUNBMSIwIAYJ\n"\
"KoZIhvcNAQkBFhNwcmF2aW5AaW5maW5lb24uY29tMB4XDTI0MDQwODA3MjExNloX\n"\
"DTI3MDEwMzA3MjExNlowgYUxCzAJBgNVBAYTAklOMQwwCgYDVQQIDANcS0ExETAP\n"\
"BgNVBAcMCEJhbmdsb3JlMREwDwYDVQQKDAhJbmZpbmVvbjELMAkGA1UECwwCQ1kx\n"\
"ETAPBgNVBAMMCG15Q2xpZW50MSIwIAYJKoZIhvcNAQkBFhNwcmF2aW5AaW5maW5l\n"\
"b24uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOGe9cWOlv9i2k1xDcfhE\n"\
"X2KrdmxZdLntsA9uHJA48k09oSUwt/bUPYojm027Kn+OBnFAiRWtNg1LMm2MYXb6\n"\
"rzAKBggqhkjOPQQDAgNIADBFAiBVUyJ3KvqiFtULixi5W2SZTAeFHnKIGiT/jhLz\n"\
"AL+2bAIhAMz157JwkPlFdbKxMcXOwWZJJ276aGDSoiJdfoTVUv7E\n"\
"-----END CERTIFICATE-----\n"

/* Private key of the TCP client. Copy from the TCP client key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keyCLIENT_PRIVATE_KEY_PEM \
"-----BEGIN EC PRIVATE KEY-----\n"\
"MHcCAQEEIBLzz4YaqTjcO/cA8dDCrzCJNku0XJBNqTOayRecnsz5oAoGCCqGSM49\n"\
"AwEHoUQDQgAEOGe9cWOlv9i2k1xDcfhEX2KrdmxZdLntsA9uHJA48k09oSUwt/bU\n"\
"PYojm027Kn+OBnFAiRWtNg1LMm2MYXb6rw==\n"\
"-----END EC PRIVATE KEY-----\n"

/* TCP server certificate. In this example this is the RootCA
 * certificate so as to verify the TCP server's identity. */
#define keySERVER_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIICWjCCAf+gAwIBAgIUei4kFRyPg1tqQgC453IS1rLS7QwwCgYIKoZIzj0EAwIw\n"\
"gYExCzAJBgNVBAYTAklOMQwwCgYDVQQIDANcS0ExETAPBgNVBAcMCEJhbmdsb3Jl\n"\
"MREwDwYDVQQKDAhJbmZpbmVvbjELMAkGA1UECwwCQ1kxDTALBgNVBAMMBG15Q0Ex\n"\
"IjAgBgkqhkiG9w0BCQEWE3ByYXZpbkBpbmZpbmVvbi5jb20wHhcNMjQwNDA4MDcy\n"\
"MDAwWhcNMjcwMTAzMDcyMDAwWjCBgTELMAkGA1UEBhMCSU4xDDAKBgNVBAgMA1xL\n"\
"QTERMA8GA1UEBwwIQmFuZ2xvcmUxETAPBgNVBAoMCEluZmluZW9uMQswCQYDVQQL\n"\
"DAJDWTENMAsGA1UEAwwEbXlDQTEiMCAGCSqGSIb3DQEJARYTcHJhdmluQGluZmlu\n"\
"ZW9uLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNtlZx0E4yb+2yXy2FKQ\n"\
"T2JOgCLHH126FKFYfm/AuByMvgQBZHSIAgp80rz3ttgrOY9x4r3YdC1tKBILctlH\n"\
"16ijUzBRMB0GA1UdDgQWBBReKAfVraHJbLK8ek775mpchP18ajAfBgNVHSMEGDAW\n"\
"gBReKAfVraHJbLK8ek775mpchP18ajAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49\n"\
"BAMCA0kAMEYCIQDAFkUC4CU3q4bpTY4UX3xCfJsPIjOjhHMv09DG2+SomwIhAIQ1\n"\
"wojOQQd/7c2v4mSi7wbmRLEJXi5mGzC7OdvXPcUC\n"\
"-----END CERTIFICATE-----\n"

#endif /* NETWORK_CREDENTIALS_H_ */
